In [1]:
import pandas as pd 
import numpy as np

In [2]:
data = pd.read_csv("cust_satisfaction.csv")
data.head()

Gender      Customer Type   Type of Travel     Class  \
0    Male     Loyal Customer  Personal Travel  Eco Plus   
1    Male  disloyal Customer  Business travel  Business   
2  Female     Loyal Customer  Business travel  Business   
3  Female     Loyal Customer  Business travel  Business   
4    Male     Loyal Customer  Business travel  Business   

              satisfaction  Age  Flight Distance  Inflight entertainment  \
0  neutral or dissatisfied   13              460                       5   
1  neutral or dissatisfied   25              235                       1   
2                satisfied   26             1142                       5   
3  neutral or dissatisfied   25              562                       2   
4                satisfied   61              214                       3   

   Baggage handling  Cleanliness  Departure Delay in Minutes  \
0                 4            5                          25   
1                 3            1                           1   
2                 4            5                           0   
3                 3            2                          11   
4                 4            3                           0   

   Arrival Delay in Minutes  
0                      18.0  
1                       6.0  
2                       0.0  
3                       9.0  
4                       0.0

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103904 entries, 0 to 103903
Data columns (total 12 columns):
 #   Column                      Non-Null Count   Dtype  
---  ------                      --------------   -----  
 0   Gender                      103904 non-null  object 
 1   Customer Type               103904 non-null  object 
 2   Type of Travel              103904 non-null  object 
 3   Class                       103904 non-null  object 
 4   satisfaction                103904 non-null  object 
 5   Age                         103904 non-null  int64  
 6   Flight Distance             103904 non-null  int64  
 7   Inflight entertainment      103904 non-null  int64  
 8   Baggage handling            103904 non-null  int64  
 9   Cleanliness                 103904 non-null  int64  
 10  Departure Delay in Minutes  103904 non-null  int64  
 11  Arrival Delay in Minutes    103594 non-null  float64
dtypes: float64(1), int64(6), object(5)
memory usage: 9.5+ MB


In [4]:
data.describe()

Age  Flight Distance  Inflight entertainment  \
count  103904.000000    103904.000000           103904.000000   
mean       39.379706      1189.448375                3.358158   
std        15.114964       997.147281                1.332991   
min         7.000000        31.000000                0.000000   
25%        27.000000       414.000000                2.000000   
50%        40.000000       843.000000                4.000000   
75%        51.000000      1743.000000                4.000000   
max        85.000000      4983.000000                5.000000   

       Baggage handling    Cleanliness  Departure Delay in Minutes  \
count     103904.000000  103904.000000               103904.000000   
mean           3.631833       3.286351                   14.815618   
std            1.180903       1.312273                   38.230901   
min            1.000000       0.000000                    0.000000   
25%            3.000000       2.000000                    0.000000   
50%            4.000000       3.000000                    0.000000   
75%            5.000000       4.000000                   12.000000   
max            5.000000       5.000000                 1592.000000   

       Arrival Delay in Minutes  
count             103594.000000  
mean                  15.178678  
std                   38.698682  
min                    0.000000  
25%                    0.000000  
50%                    0.000000  
75%                   13.000000  
max                 1584.000000

In [5]:
data.shape

(103904, 12)

In [6]:
data.columns

Index(['Gender', 'Customer Type', 'Type of Travel', 'Class', 'satisfaction',
       'Age', 'Flight Distance', 'Inflight entertainment', 'Baggage handling',
       'Cleanliness', 'Departure Delay in Minutes',
       'Arrival Delay in Minutes'],
      dtype='object')

In [ ]:


data['Customer Type'].unique()

array(['Loyal Customer', 'disloyal Customer'], dtype=object)

In [ ]:


data['Type of Travel'].unique()

array(['Personal Travel', 'Business travel'], dtype=object)

In [13]:

data['Class'].unique()



array(['Eco Plus', 'Business', 'Eco'], dtype=object)

In [14]:
data['satisfaction'].unique()



array(['neutral or dissatisfied', 'satisfied'], dtype=object)

In [15]:
data['Age'].unique()


array([13, 25, 26, 61, 47, 52, 41, 20, 24, 12, 53, 33, 45, 38,  9, 17, 43,
       58, 23, 57, 49, 36, 22, 31, 15, 35, 67, 37, 40, 34, 39, 50, 29, 54,
       21, 28, 27, 69, 60, 48, 59, 46, 30, 66, 64, 44, 51, 32, 19, 42, 16,
       11, 62,  8, 56, 68, 55, 18, 65, 72, 70, 63, 10,  7, 14, 80, 74, 71,
       85, 73, 76, 77, 75, 79, 78], dtype=int64)

In [16]:

data['Flight Distance'].unique()


array([ 460,  235, 1142, ...,  974, 1479,  400], dtype=int64)

In [31]:
data['Flight Distance'].astype(str).str.isnumeric().sum()


103422

In [28]:
data.shape

(103422, 12)

In [17]:

data['Inflight entertainment'].unique()



array([5, 1, 2, 3, 4, 0], dtype=int64)

In [18]:
data['Baggage handling'].unique()

array([4, 3, 5, 1, 2], dtype=int64)

In [19]:
data.isnull().sum()

Gender                          0
Customer Type                   0
Type of Travel                  0
Class                           0
satisfaction                    0
Age                             0
Flight Distance                 0
Inflight entertainment          0
Baggage handling                0
Cleanliness                     0
Departure Delay in Minutes      0
Arrival Delay in Minutes      310
dtype: int64

In [20]:
data.dropna(inplace=True)

In [21]:
data[data.duplicated()]

Gender      Customer Type   Type of Travel     Class satisfaction  \
2741      Male     Loyal Customer  Business travel  Business    satisfied   
5228      Male  disloyal Customer  Business travel       Eco    satisfied   
6278    Female  disloyal Customer  Business travel  Business    satisfied   
7330      Male     Loyal Customer  Business travel  Business    satisfied   
8405      Male     Loyal Customer  Business travel  Business    satisfied   
...        ...                ...              ...       ...          ...   
102110    Male     Loyal Customer  Business travel  Business    satisfied   
102327    Male     Loyal Customer  Business travel  Business    satisfied   
102679  Female     Loyal Customer  Business travel  Business    satisfied   
102801    Male     Loyal Customer  Business travel  Business    satisfied   
103627    Male     Loyal Customer  Business travel  Business    satisfied   

        Age  Flight Distance  Inflight entertainment  Baggage handling  \
2741     56             1535                       5                 5   
5228     20              861                       2                 5   
6278     21              448                       2                 5   
7330     49              258                       4                 4   
8405     53             2149                       4                 4   
...     ...              ...                     ...               ...   
102110   45             1389                       5                 5   
102327   56              444                       5                 5   
102679   44              862                       5                 5   
102801   48             3354                       4                 4   
103627   46              945                       4                 4   

        Cleanliness  Departure Delay in Minutes  Arrival Delay in Minutes  
2741              3                           0                       0.0  
5228              2                           0                       0.0  
6278              2                           0                       0.0  
7330              4                           0                       0.0  
8405              3                           0                       0.0  
...             ...                         ...                       ...  
102110            3                           0                       0.0  
102327            5                           1                       0.0  
102679            5                           0                       0.0  
102801            4                           0                       0.0  
103627            4                           0                       0.0  

[172 rows x 12 columns]

In [22]:
data.drop_duplicates(inplace=True)

In [23]:
data.shape

(103422, 12)

In [33]:
numeric_features = [feature for feature in data.columns if data[feature].dtype != 'O']
categorical_features = [feature for feature in data.columns if data[feature].dtype == 'O']

# print columns
print('We have {} numerical features : {}'.format(len(numeric_features), numeric_features))
print('\nWe have {} categorical features : {}'.format(len(categorical_features), categorical_features))

We have 7 numerical features : ['Age', 'Flight Distance', 'Inflight entertainment', 'Baggage handling', 'Cleanliness', 'Departure Delay in Minutes', 'Arrival Delay in Minutes']

We have 5 categorical features : ['Gender', 'Customer Type', 'Type of Travel', 'Class', 'satisfaction']
